depthimage_to_laserscan_node:
  ros__parameters:
    range_min: 0.1
    range_max: 10.0
    scan_height: 10
    output_frame: "camera_depth_frame"
    scan_time: 0.033
    min_height: 10
    max_height: 20
