amcl:
  use_sim_time: false

bt_navigator:
  plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_goal_checker_condition_bt_node
    - nav2_controller_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_path_valid_condition_bt_node
    - nav2_recovery_node_bt_node
    - nav2_pipeline_sequence_bt_node

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_plugins: ["FollowPath"]
    
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller/RegulatedPurePursuitController"
      desired_linear_vel: 1.5
      max_linear_accel: 1.0
      max_angular_vel: 1.5
      lookahead_dist: 1.2
      min_lookahead_dist: 0.8
      max_lookahead_dist: 2.0
      lookahead_time: 1.5
      use_velocity_scaled_lookahead_dist: true

      use_regulated_linear_velocity_scaling: true
      regulated_linear_scaling_min_speed: 0.25
      regulated_linear_scaling_min_radius: 1.5

      use_rotate_to_heading: false
      allow_reversing: true
      transform_tolerance: 0.2
      min_approach_linear_velocity: 0.1
      approach_velocity_scaling_dist: 0.5

planner_server:
  ros__parameters:
    use_sim_time: false
    planner_plugins: ["GridBased"]
    
    GridBased:
      plugin: "nav2_smac_planner/SmacPlannerHybrid"
      allow_unknown: true
      tolerance: 0.25
      max_planning_time: 5.0
      motion_model_for_search: "REEDS_SHEPP"
      minimum_turning_radius: 1.36
      reverse_penalty: 1.5
      non_straight_penalty: 1.2
      cost_penalty: 1.7
      downsample_costmap: false
      analytic_expansion_max_length: 3.0
      analytic_expansion_max_cost: 400.0

global_costmap:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 5.0
    publish_frequency: 1.0
    resolution: 0.05
    rolling_window: false
    width: 30.0
    height: 30.0
    footprint: [[0.336, 0.308], [0.336, -0.308], [-0.336, -0.308], [-0.336, 0.308]]

    plugins:
      - obstacle_layer
      - inflation_layer

    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      enabled: true
      max_obstacle_height: 0.4
      obstacle_max_range: 3.0
      raytrace_max_range: 4.0

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      enabled: true
      inflation_radius: 0.9
      cost_scaling_factor: 2.5

local_costmap:
  ros__parameters:
    use_sim_time: false
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 10.0
    publish_frequency: 5.0
    resolution: 0.05
    rolling_window: true
    width: 6.0
    height: 6.0
    footprint: [[0.336, 0.308], [0.336, -0.308], [-0.336, -0.308], [-0.336, 0.308]]

    plugins:
      - obstacle_layer
      - inflation_layer

    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      enabled: true
      max_obstacle_height: 0.4
      obstacle_max_range: 3.0
      raytrace_max_range: 4.0

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      enabled: true
      inflation_radius: 0.9
      cost_scaling_factor: 2.5

behavior_tree:
  ros__parameters:
    use_sim_time: false
    default_nav_to_pose_bt_xml: "navigate_w_replanning_and_recovery.xml"

goal_checker:
  ros__parameters:
    stateful: true
    xy_goal_tolerance: 0.2
    yaw_goal_tolerance: 0.2

progress_checker:
  ros__parameters:
    required_movement_radius: 0.5
    movement_time_allowance: 10.0
