# Unique camera name
camera_name: "camera"  # camera unique name

# Namespace for the camera node
camera_namespace: "camera"  # namespace for camera

# Device selection (choose device by serial number, USB port, or type)
serial_no: ""            # choose device by serial number
usb_port_id: ""          # choose device by usb port id
device_type: ""          # choose device by type

# Config files for advanced settings
config_file: ""          # yaml config file
json_file_path: ""       # allows advanced configuration

# Device initialization/reset options
initial_reset: "false"   # (no description)
accelerate_gpu_with_glsl: "false"  # enable GPU acceleration with GLSL

# Play from rosbag file instead of live device
rosbag_filename: ""      # A realsense bagfile to run from as a device

# Logging and output
log_level: "info"        # debug log level [DEBUG|INFO|WARN|ERROR|FATAL]
output: "screen"         # pipe node output [screen|log]

# Enable/disable streams
enable_color: "true"     # enable color stream
rgb_camera.color_profile: "0,0,0"   # color stream profile
rgb_camera.color_format: "RGB8"     # color stream format
rgb_camera.enable_auto_exposure: "true"  # enable/disable auto exposure for color image

enable_depth: "true"     # enable depth stream
enable_infra: "false"    # enable infra0 stream
enable_infra1: "false"   # enable infra1 stream
enable_infra2: "false"   # enable infra2 stream

depth_module.depth_profile: "0,0,0"    # depth stream profile
depth_module.depth_format: "Z16"       # depth stream format
depth_module.infra_profile: "0,0,0"    # infra streams (0/1/2) profile
depth_module.infra_format: "RGB8"      # infra0 stream format
depth_module.infra1_format: "Y8"       # infra1 stream format
depth_module.infra2_format: "Y8"       # infra2 stream format

depth_module.exposure: "8500"           # Depth module manual exposure value
depth_module.gain: "16"                  # Depth module manual gain value
depth_module.hdr_enabled: "false"       # Depth module hdr enablement flag. Used for hdr_merge filter
depth_module.enable_auto_exposure: "true"  # enable/disable auto exposure for depth image

depth_module.exposure.1: "7500"          # Depth module first exposure value. Used for hdr_merge filter
depth_module.gain.1: "16"                 # Depth module first gain value. Used for hdr_merge filter
depth_module.exposure.2: "1"              # Depth module second exposure value. Used for hdr_merge filter
depth_module.gain.2: "16"                 # Depth module second gain value. Used for hdr_merge filter

# Sync and RGBD options
enable_sync: "false"       # enable sync mode
enable_rgbd: "false"       # enable rgbd topic

# IMU options
enable_gyro: "false"       # enable gyro stream
enable_accel: "false"      # enable accel stream
gyro_fps: "0"              # gyro frames per second
accel_fps: "0"             # accel frames per second
unite_imu_method: "0"      # [0-None, 1-copy, 2-linear_interpolation]

# Advanced filtering and transforms
clip_distance: "-2."       # clip distance
angular_velocity_cov: "0.01"  # angular velocity covariance
linear_accel_cov: "0.01"      # linear acceleration covariance
diagnostics_period: "0.0"     # Rate of publishing diagnostics. 0=Disabled

publish_tf: "true"           # enable/disable publishing static & dynamic TF
tf_publish_rate: "0.0"       # rate in Hz for publishing dynamic TF

pointcloud.enable: "false"               # enable pointcloud generation
pointcloud.stream_filter: "2"            # texture stream for pointcloud
pointcloud.stream_index_filter: "0"      # texture stream index for pointcloud
pointcloud.ordered_pc: "false"            # ordered pointcloud flag
pointcloud.allow_no_texture_points: "false"  # allow points without texture

# Filters
align_depth.enable: "false"          # enable align depth filter
colorizer.enable: "false"            # enable colorizer filter
decimation_filter.enable: "false"    # enable decimation filter
spatial_filter.enable: "false"       # enable spatial filter
temporal_filter.enable: "false"      # enable temporal filter
disparity_filter.enable: "false"     # enable disparity filter
hole_filling_filter.enable: "false"  # enable hole filling filter
hdr_merge.enable: "false"             # hdr_merge filter enablement flag

# Timeouts and reconnects
wait_for_device_timeout: "-1."    # Timeout for waiting for device to connect (Seconds)
reconnect_timeout: "6."           # Timeout(seconds) between consecutive reconnection attempts
