slam_toolbox:
  ros__parameters:
    # -----------------------------
    # to fix error 'discarding message because the queue is full'
    # -----------------------------
    queue_size: 30  # Add this if not already presen
    throttle_scans: 2

    
    # -----------------------------
    # Solver Configuration (still needed internally)
    # -----------------------------
    solver_plugin: "solver_plugins::CeresSolver"
    ceres_linear_solver: "SPARSE_NORMAL_CHOLESKY"
    ceres_preconditioner: "SCHUR_JACOBI"
    ceres_trust_strategy: "LEVENBERG_MARQUARDT"
    ceres_dogleg_type: "TRADITIONAL_DOGLEG"
    ceres_loss_function: "None"

    # -----------------------------
    # Frame and Topic Names
    # -----------------------------
    odom_frame: "odom"
    map_frame: "map"
    base_frame: "base_footprint"
    scan_topic: "/scan"

    # -----------------------------
    # Operating Mode
    # -----------------------------
    mode: "localization"             # <== KEY difference from mapping mode

    # -----------------------------
    # Map loading
    # -----------------------------
    map_file_name: "my_map"          # Replace with your actual .posegraph or serialized map file
    # map_start_pose: [x, y, yaw]    # Optional: initial guess for pose
    # map_start_at_dock: false       # Optional: if used with dock system

    # -----------------------------
    # System Behavior
    # -----------------------------
    use_map_saver: false             # Not saving maps during localization
    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.02
    map_update_interval: 2.0         # Slightly more frequent than mapping mode
    resolution: 0.05
    min_laser_range: 0.0
    max_laser_range: 20.0
    minimum_time_interval: 0.5
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    stack_size_to_use: 40000000
    enable_interactive_mode: true

    # -----------------------------
    # Scan Matching Parameters
    # -----------------------------
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.2     # Smaller since we're tracking pose
    minimum_travel_heading: 0.2
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5

    # -----------------------------
    # Loop Closure Parameters
    # -----------------------------
    do_loop_closing: false           # Usually disabled in localization mode

    # -----------------------------
    # Correlation Parameters
    # -----------------------------
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1

    # -----------------------------
    # Scan Matcher Tuning
    # -----------------------------
    distance_variance_penalty: 0.5
    angle_variance_penalty: 1.0
    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.349
    coarse_angle_resolution: 0.0349
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true
    min_pass_through: 2
    occupancy_threshold: 0.1
