
slam_toolbox:
  ros__parameters:

    # -----------------------------
    # Solver Configuration
    # -----------------------------
    solver_plugin: "solver_plugins::CeresSolver"  # Backend optimization solver
    ceres_linear_solver: "SPARSE_NORMAL_CHOLESKY"
    ceres_preconditioner: "SCHUR_JACOBI"
    ceres_trust_strategy: "LEVENBERG_MARQUARDT"
    ceres_dogleg_type: "TRADITIONAL_DOGLEG"
    ceres_loss_function: "None"

    # -----------------------------
    # Frame and Topic Names
    # -----------------------------
    odom_frame: "odom"               # Odometry frame
    map_frame: "map"                 # Map frame
    base_frame: "base_footprint"     # Robot base frame
    scan_topic: "/scan"              # LaserScan topic

    # -----------------------------
    # Operating Mode
    # -----------------------------
    mode: "mapping"                  # Options: mapping or localization

    # -----------------------------
    # Startup Options (uncomment if needed)
    # -----------------------------
    # map_file_name: "my_map"        # Optional: continue from saved map
    # map_start_pose: [0.0, 0.0, 0.0] # Initial pose to start from
    # map_start_at_dock: true        # Start map from docking station pose

    # -----------------------------
    # System Behavior
    # -----------------------------
    use_map_saver: true              # Automatically save map
    debug_logging: false             # Enable debug output
    throttle_scans: 1                # Use every scan (1 = no throttling)
    transform_publish_period: 0.02   # Frequency of transform publishing (s)
    map_update_interval: 5.0         # How often the map is updated (s)
    resolution: 0.05                 # Map resolution (m/cell)
    min_laser_range: 0.0             # Minimum LaserScan range (m)
    max_laser_range: 20.0            # Maximum LaserScan range (m)
    minimum_time_interval: 0.5       # Minimum time between scan matching (s)
    transform_timeout: 0.2           # Timeout for TF transforms (s)
    tf_buffer_duration: 30.0         # Duration of stored TFs (s)
    stack_size_to_use: 40000000      # Stack size for large map serialization
    enable_interactive_mode: true    # Enable RViz interactive pose

    # -----------------------------
    # Scan Matching Parameters
    # -----------------------------
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.5     # Minimum distance before update (m)
    minimum_travel_heading: 0.5      # Minimum angle before update (rad)
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5

    # -----------------------------
    # Loop Closure Parameters
    # -----------------------------
    do_loop_closing: true
    loop_search_maximum_distance: 3.0
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45

    # -----------------------------
    # Correlation Parameters (Local)
    # -----------------------------
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1

    # -----------------------------
    # Correlation Parameters (Loop Closure)
    # -----------------------------
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # -----------------------------
    # Scan Matcher Tuning
    # -----------------------------
    distance_variance_penalty: 0.5
    angle_variance_penalty: 1.0
    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.349
    coarse_angle_resolution: 0.0349
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true
    min_pass_through: 2
    occupancy_threshold: 0.1
