twist_mux:
  ros__parameters:
    topics:
      drive_test:
        topic   : cmd_vel
        timeout : 0.1
        priority: 10
      nav2:
        topic   : cmd_vel_nav
        timeout : 0.1
        priority: 100
     
