twist_mux:
  ros__parameters:
    topics:
      drive_test:
        topic   : cmd_vel_drive
        timeout : 0.1
        priority: 10
      othrsCMD:
        topic   : cmd_vel_tool
        timeout : 0.1
        priority: 100
     
