twist_mux:
  ros__parameters:
    topics:
      drive_test:
        topic   : cmd_vel_drive
        timeout : 0.1
        priority: 1
      nav2:
        topic   : cmd_vel
        timeout : 0.1
        priority: 100
     
